### ISSUE TITLE
TypeScript + npm link

### ISSUE THREAD

**Issue by vweevers** [Level/memdown#101]
When I `cd memdown && git co v2 && npm link abstract-leveldown && npm t`, TypeScript doesn't compile, with many errors like:

```
TSError: ⨯ Unable to compile TypeScript
..\abstract-leveldown\abstract-leveldown.js (34,19): Property '_open' does not exist on type '{ location: string; status: string; open: (options: any, callback: any) => void; close: (callback...'. Did you mean 'open'? (2551)
..\abstract-leveldown\abstract-leveldown.js (92,19): Property '_get' does not exist on type '{ location: string; status: string; open: (options: any, callback: any) => void; close: (callback...'. Did you mean 'get'? (2551)
```

Doesn't happen with a regular `npm i abstract-leveldown` or `npm i level/abstract-leveldown` (which is the same version as I have on disk and want to link).

@MeirionHughes any idea?

**Comment by MeirionHughes** [comment]
yeah, this caused me unbelievable pain on levelup. The problem is that when you use a link, then typescript will include the linked source when it compiles. Then, because things like `_open` and `_get` are not explicitly defined on abstract down, it complains about it. There are two solutions: define the `virtual` functions with `AbstractLevelDown.prototype._open = undefined` or don't use the link: `npm install ../abstract-leveldown`

**Comment by vweevers** [comment]
> or don't use the link: npm install ../abstract-leveldown

Thanks, I'll try that. Is there a typescript issue I can subscribe to? I do hope they intend to fix this.

**Comment by vweevers** [comment]
Doesn't have to be solved before v2.

**Comment by vweevers** [comment]
Doesn't seem to happen anymore.
